/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FuncionarioDb;
import JTPadrao.JCTable;
import Swing.Panel.CPanel;
import java.util.HashMap;

/**
 *
 * @author Cristian
 */
public class ConsultaFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaFuncionario
     */
    public ConsultaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Filtro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cdFuncionarioJTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nmFuncionarioJTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nrTelefoneJTF = new javax.swing.JTextField();
        pesquisarJB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCTable1 = new JTPadrao.JCTable();

        setLayout(new java.awt.BorderLayout());

        Filtro.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setText("Código:");

        cdFuncionarioJTF.setAlignmentY(1.0F);

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        pesquisarJB.setText("Pesquisar");
        pesquisarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cdFuncionarioJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(pesquisarJB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmFuncionarioJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrTelefoneJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cdFuncionarioJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nmFuncionarioJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrTelefoneJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Filtro.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(Filtro, java.awt.BorderLayout.NORTH);

        jCTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jCTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarJBActionPerformed
        HashMap colunas = new HashMap();
        colunas.put("CD_FUNCIONARIO", null);
        colunas.put("NM_FUNCIONARIO", null);
        colunas.put("DS_LOGIN", null);
        colunas.put("DS_SENHA", null);

        HashMap restricoes = new HashMap();
        //restricoes.put("CD_FUNCIONARIO", "'"+cdFuncionarioJTF.getText()+"'");
        restricoes.put("NM_FUNCIONARIO", "'"+nmFuncionarioJTF.getText()+"'");
        //restricoes.put("NR_TELEFONE", "'"+nrTelefoneJTF.getText()+"'");

        FuncionarioDb fDB = new FuncionarioDb();
        jCTable1 = new JCTable(fDB.getFuncionarios(colunas, restricoes, null));
        jScrollPane1.setViewportView(jCTable1);
        jCTable1.validate();

    }//GEN-LAST:event_pesquisarJBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Filtro;
    private javax.swing.JTextField cdFuncionarioJTF;
    private JTPadrao.JCTable jCTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmFuncionarioJTF;
    private javax.swing.JTextField nrTelefoneJTF;
    private javax.swing.JButton pesquisarJB;
    // End of variables declaration//GEN-END:variables
}
