/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

    private Principal principal;
    private boolean isCadastroFuncionarioAberto;
    private boolean isCadastroProdutoAberto;

    /**
     * Creates new form pRINCIPAL
     */
    public Principal() {
        principal = this;
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        funcuinaMI = new javax.swing.JMenuItem();
        produtoJMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        BuscaFuncionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        funcuinaMI.setText("Funcionarios");
        funcuinaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcuinaMIActionPerformed(evt);
            }
        });
        jMenu1.add(funcuinaMI);

        produtoJMI.setText("Produtos");
        produtoJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoJMIActionPerformed(evt);
            }
        });
        jMenu1.add(produtoJMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Busca");

        BuscaFuncionario.setText("jMenuItem1");
        BuscaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(BuscaFuncionario);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcuinaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcuinaMIActionPerformed
        abreJanela(new CadastroFuncionario());
    }//GEN-LAST:event_funcuinaMIActionPerformed

    private void produtoJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoJMIActionPerformed
        abreJanela(new CadastroProduto());
    }//GEN-LAST:event_produtoJMIActionPerformed

    private void BuscaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaFuncionarioActionPerformed
        abreJanela(new ConsultaFuncionario());
    }//GEN-LAST:event_BuscaFuncionarioActionPerformed

    private void abreJanela(JPanel jPanel) {
        boolean abrirJanela = true;
        if (jPanel instanceof CadastroFuncionario) {
            if (!isCadastroFuncionarioAberto) {
                isCadastroFuncionarioAberto = true;
                abrirJanela = true;
            }
        } else {
            if (jPanel instanceof CadastroProduto) {
                if (!isCadastroProdutoAberto) {
                    isCadastroProdutoAberto = true;
                    abrirJanela = true;
                }
            }
        }

        if (abrirJanela) {
            JDialog dialogBoxJD = new JDialog(this);
            dialogBoxJD.setName(jPanel.getName());
            dialogBoxJD.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent we) {
                    switch (we.getWindow().getName()) {
                        case "cadastroFuncionario": {
                            isCadastroFuncionarioAberto = false;
                            break;
                        }
                        case "cadastroProduto": {
                            isCadastroProdutoAberto = false;
                            break;
                        }
                    }
                }

            });
            dialogBoxJD.add(jPanel);
            dialogBoxJD.setSize(jPanel.getPreferredSize());
            dialogBoxJD.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuscaFuncionario;
    private javax.swing.JMenuItem funcuinaMI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem produtoJMI;
    // End of variables declaration//GEN-END:variables
}
